CREATE DATABASE DBB15;
USE DBB15;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20),
    EMP_SALARY INT
);
INSERT INTO EMPLOYEES VALUES (101,"E1",10000),(102,"E2",20000);
SELECT * FROM EMPLOYEES;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;


START TRANSACTION;
DELETE FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;
ROLLBACK;
SELECT * FROM EMPLOYEES;

START TRANSACTION;
DELETE FROM EMPLOYEES
WHERE EMP_ID = 102;
SELECT * FROM EMPLOYEES;
COMMIT;


CREATE TABLE DEPARTMENTS(
	DEPT_ID INT,
    DEPT_NAME VARCHAR(20)
);

CREATE TABLE EMPLOYEES1(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    EMP_EMAIL VARCHAR(20),
    EMP_SALARY INT
);

DESCRIBE DEPARTMENTS;

ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY (DEPT_ID);
DESCRIBE DEPARTMENTS;

DESCRIBE EMPLOYEES1;
ALTER TABLE EMPLOYEES1
ADD PRIMARY KEY (EMP_ID);
DESCRIBE EMPLOYEES1;

ALTER TABLE EMPLOYEES1
ADD UNIQUE (EMP_EMAIL);
DESCRIBE EMPLOYEES1;


ALTER TABLE EMPLOYEES1
ADD COLUMN DEPT_ID INT;

SELECT * FROM EMPLOYEES1;

ALTER TABLE EMPLOYEES1
ADD CONSTRAINT FK_DEPT_ID
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID);

DESCRIBE EMPLOYEES1;