CREATE DATABASE DB21;
USE DB21;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL,
    AGE INT NOT NULL,
    CITY VARCHAR(20) NOT NULL
);
INSERT INTO employees (emp_id, name, department, salary, age, city) VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN (
	SELECT DEPARTMENT FROM EMPLOYEES
    WHERE CITY = "DELHI"
);
SELECT * FROM EMPLOYEES
WHERE SALARY IN (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "HR";
SELECT * FROM EMPLOYEES;
SET SQL_SAFE_UPDATES = 0;
UPDATE EMPLOYEES SET SALARY = 40000 
WHERE EMP_ID = 6;

SELECT * FROM EMPLOYEES
WHERE CITY IN (
	SELECT CITY FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);
SELECT CITY FROM EMPLOYEES
WHERE DEPARTMENT = "IT";

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "HR";

SELECT * FROM EMPLOYEES
WHERE SALARY > ANY (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT AGE FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE";

SELECT * FROM EMPLOYEES
WHERE AGE > ANY (
	SELECT AGE FROM EMPLOYEES
	WHERE DEPARTMENT = "FINANCE"
);

SELECT SALARY FROM EMPLOYEES
WHERE CITY = "MUMBAI";

SELECT * FROM EMPLOYEES
WHERE SALARY < ANY (
	SELECT SALARY FROM EMPLOYEES
	WHERE CITY = "MUMBAI"
);


SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "HR";

SELECT * FROM EMPLOYEES
WHERE SALARY < ALL (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES
WHERE SALARY < ALL (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);

SELECT SALARY FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE";

SELECT * FROM EMPLOYEES
WHERE SALARY < ALL (
	SELECT SALARY FROM EMPLOYEES
	WHERE DEPARTMENT = "FINANCE"
);

SELECT * FROM EMPLOYEES E1
WHERE SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT = E1.DEPARTMENT
);

SELECT * FROM EMPLOYEES AS E1
WHERE AGE > (
	SELECT AVG(AGE) FROM EMPLOYEES AS E2
    WHERE E2.CITY = E1.CITY
);

SELECT * FROM EMPLOYEES E1
WHERE SALARY >= (
	SELECT MAX(SALARY) FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT = E1.DEPARTMENT
);

SELECT * FROM EMPLOYEES AS E1
WHERE AGE = (
	SELECT MIN(AGE) FROM EMPLOYEES E2
    WHERE E2.DEPARTMENT = E1.DEPARTMENT
);

SELECT * FROM EMPLOYEES E1
WHERE SALARY < ANY (
	SELECT SALARY FROM EMPLOYEES E2
    WHERE E2.CITY = E1.CITY
);