CREATE DATABASE DB9;
USE DB9;

CREATE TABLE DEPARTMENTS(
	DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(10) NOT NULL
);
INSERT INTO DEPARTMENTS VALUES (101,"IT"),(102,"HR");
SELECT * FROM DEPARTMENTS;

CREATE TABLE EMPLOYEES1(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20) NOT NULL,
    DEPT_ID INT
);
INSERT INTO EMPLOYEES1 VALUES (1,"E1",101);
SELECT * FROM EMPLOYEES1;
INSERT INTO EMPLOYEES1 VALUES (2,"E2",102);
SELECT * FROM EMPLOYEES1;
INSERT INTO EMPLOYEES1 VALUES (3,"E3",103);
SELECT * FROM EMPLOYEES1;

CREATE TABLE EMPLOYEES2(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20) NOT NULL,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);
INSERT INTO EMPLOYEES2 VALUES (1,"E1",101);
SELECT * FROM EMPLOYEES2;
INSERT INTO EMPLOYEES2 VALUES (2,"E2",102);
SELECT * FROM EMPLOYEES2;
INSERT INTO EMPLOYEES2 VALUES (3,"E3",103);
SELECT * FROM EMPLOYEES2;


CREATE TABLE AUTHORS(
	AUTHOR_ID INT PRIMARY KEY,
    AUTHON_NAME VARCHAR(20) NOT NULL
);
INSERT INTO AUTHORS VALUES (101,"A1"),(102,"A2");
SELECT * FROM AUTHORS;

CREATE TABLE BOOKS(
	BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(10) NOT NULL,
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);
INSERT INTO BOOKS VALUES (1,"B1",101);
INSERT INTO BOOKS VALUES (2,"B2",102);
INSERT INTO BOOKS VALUES (3,"B3",103);
SELECT * FROM BOOKS;


CREATE TABLE COURSES(
	COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(10) NOT NULL
);
INSERT INTO COURSES VALUES (1,"PYTHON");
INSERT INTO COURSES VALUES (2,"JAVA");
INSERT INTO COURSES VALUES (3,"MYSQL");
SELECT * FROM COURSES;

CREATE TABLE EXAMS(
	EXAM_ID INT PRIMARY KEY,
    EXAM_DATE DATE,
    CID INT,
    FOREIGN KEY (CID) REFERENCES COURSES(COURSE_ID)
);
INSERT INTO EXAMS VALUES (101,"2024-8-24",1);
SELECT * FROM EXAMS;
INSERT INTO EXAMS VALUES (102,"2024-9-24",2);
SELECT * FROM EXAMS;
INSERT INTO EXAMS VALUES (103,"2024-10-24",3);
SELECT * FROM EXAMS;
INSERT INTO EXAMS VALUES (104,"2024-11-24",4);
SELECT * FROM EXAMS;