CREATE DATABASE DB19;
USE DB19;

CREATE TABLE STUDENTS(
	ID INT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    MARKS INT NOT NULL DEFAULT 0,
    BRANCH VARCHAR(10) NOT NULL
);

CREATE USER "MANAGER101" IDENTIFIED BY "1234";
CREATE USER "MANAGER202" IDENTIFIED BY "5678";


GRANT INSERT ON STUDENTS TO MANAGER101;
GRANT SELECT ON STUDENTS TO MANAGER101;
GRANT UPDATE ON STUDENTS TO MANAGER101;

GRANT SELECT ON STUDENTS TO MANAGER202;
GRANT UPDATE ON STUDENTS TO MANAGER202;
GRANT DELETE ON STUDENTS TO MANAGER202;
GRANT INSERT ON STUDENTS TO MANAGER202;


REVOKE UPDATE ON STUDENTS FROM MANAGER101;

