CREATE DATABASE HELLO4;
USE HELLO4;

CREATE TABLE TABLE1(
	COL1 CHAR(5)
);
SELECT * FROM TABLE1;
INSERT INTO TABLE1 VALUES ("A");
SELECT * FROM TABLE1;
INSERT INTO TABLE1 VALUES ("ABCD");
SELECT * FROM TABLE1;
INSERT INTO TABLE1 VALUES ("ABCDEFG");
SELECT * FROM TABLE1;

CREATE TABLE TABLE2(
	COL1 CHAR(5),
    COL2 VARCHAR(5)
);
INSERT INTO TABLE2 VALUES ("A","A");
SELECT * FROM TABLE2;
INSERT INTO TABLE2 VALUES ("ABCDEF","ABCDEF");

CREATE TABLE TABLE3(
	COL1 CHAR(5),
    COL2 CHAR(5),
    COL3 BINARY(5)
);
INSERT INTO TABLE3 VALUES ("HELLO","HELLO","HELLO");
SELECT * FROM TABLE3;
INSERT INTO TABLE3 VALUES ("HELLO","HELLO","HELLO WORLD");

CREATE TABLE TABLE4(
	COL1 CHAR(5),
    COL2 VARCHAR(5),
    COL3 BINARY(5),
    COL4 VARBINARY(5)
);
INSERT INTO TABLE4 VALUES ("HELLO","HELLO","HELLO","HELLO");
SELECT * FROM TABLE4;


CREATE TABLE TABLE5(
	COL1 BLOB
);
INSERT INTO TABLE5 VALUES ("HELLO");
SELECT * FROM TABLE5;