CREATE DATABASE DBB10;
USE DBB10;

CREATE TABLE EMPLOYEES(
	EMPID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(10) NOT NULL,
    LASTNAME VARCHAR(10),
    EMAIL VARCHAR(20),
    DEPARTMENT VARCHAR(20),
    SALARY INT CHECK (SALARY > 0),
    DOJ DATE
);
INSERT INTO EmployeeS VALUES 
(101, 'Alice', 'Johnson', 'alice.j@gmail.com', 'HR', 55000.00, '2022-03-01'),
(102, 'Bob', 'Smith', 'bob.smith@gmail.com', 'Sales', 60000.00, '2023-07-15'),
(103, 'Charlie', NULL, 'charlie.c@gmail.com', 'IT', 70000.00, '2021-11-20'),
(104, 'Diana', 'Stone', 'diana.s@gmail.com', 'HR', 58000.00, '2024-01-10'),
(105, 'Ethan', 'Miles', 'ethan.m@gmail.com', 'Finance', 49000.00, '2023-05-05');
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT = "HR";
SET SQL_SAFE_UPDATES = 0;

UPDATE EMPLOYEES SET SALARY = SALARY + SALARY * 0.10
WHERE DEPARTMENT = "HR";

UPDATE EMPLOYEES SET DEPARTMENT = "HUMAN RESOURCES"
WHERE DEPARTMENT = "HR";
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
ADD COLUMN PHONE VARCHAR(20);
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
MODIFY DEPARTMENT VARCHAR(100);
DESCRIBE EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY > 50000;

SELECT * FROM EMPLOYEES
WHERE DOJ > "2023-01-01";

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME LIKE "A%";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = "SALES" OR DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN ("SALES","IT");

SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS FULLNAME 
FROM EMPLOYEES;


SELECT FIRSTNAME,LENGTH(FIRSTNAME) AS LENGTH
FROM EMPLOYEES;

SELECT FIRSTNAME,CHAR_LENGTH(FIRSTNAME) AS LENGTH
FROM EMPLOYEES;

SELECT EMPID,FIRSTNAME,UPPER(LASTNAME) AS LASTNAME,SALARY
FROM EMPLOYEES;

SELECT FIRSTNAME,SUBSTRING(FIRSTNAME,1,3) AS SUB_NAME
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 40000 AND 80000;

SELECT * FROM EMPLOYEES
WHERE SALARY > 40000 AND SALARY < 80000;

SELECT * FROM EMPLOYEES
WHERE EMAIL LIKE "%GMAIL.COM";

SELECT * FROM EMPLOYEES
WHERE NOT DEPARTMENT = "FINANCE";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT != "FINANCE";

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME = "JOHN" AND DEPARTMENT = "SALES";

SELECT * FROM EMPLOYEES
WHERE LASTNAME IS NULL;

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME LIKE "%E%";

SELECT * FROM EMPLOYEES
WHERE LASTNAME LIKE "%N";

SELECT * FROM EMPLOYEES
WHERE NOT EMAIL LIKE "%@GMAIL.COM";

SELECT FIRSTNAME,DEPARTMENT,LENGTH(DEPARTMENT) AS LENGTH
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE LASTNAME IS NULL OR LASTNAME LIKE "J%";

DELETE FROM EMPLOYEES
WHERE DEPARTMENT = "HUMAN RESOURCES";
SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES SET PHONE = "100"
WHERE DEPARTMENT IN ("IT","FINANCE");
SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES SET DOJ = current_date()
WHERE DEPARTMENT = "SALES";
SELECT * FROM EMPLOYEES;

ALTER TABLE EMPLOYEES
DROP COLUMN EMAIL;
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE FIRSTNAME = REVERSE(FIRSTNAME);