CREATE DATABASE DB4;
USE DB4;

CREATE TABLE EMPLOYEES(
	EMP_ID INT,
    EMP_NAME VARCHAR(50),
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE
);

CREATE TABLE PRODUCTS(
	PRODCUT_ID INT,
    PRODUCT_NAME VARCHAR(50),
    PRICE FLOAT,
    MANFACTURING_DATE DATE
);

CREATE TABLE STUDENTS(
	STUDENT_ID SMALLINT,
    STUDENT_NAME VARCHAR(50),
    AGE TINYINT,
    HEIGHT FLOAT
);

CREATE TABLE ARTICLES(
	ARTICLE_ID INT,
    TITLE VARCHAR(200),
    CONTENT TEXT
);

CREATE TABLE EMPLOYEES1(
	EMP_ID INT,
    EMP_NAME VARCHAR(50),
    GENDER ENUM("MALE","FEMALE","OTHERS"),
    JOBROLE ENUM("DEVELOPER","MANAGER","TESTER")
);

CREATE TABLE STUDENTS1(
	STUDENT_ID INT,
    STUDENT_NAME VARCHAR(50),
    HOBBILES SET("READING","MUSIC","SPORTS")
);

CREATE TABLE MEMBERS(
	MEMBER_ID INT,
    MEMBER_NAME VARCHAR(50),
    MEMBERSHIP ENUM("GOLD","SILVER","PLATINUM")
);