CREATE DATABASE DB18;
USE DB18;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(20) NOT NULL,
    EMP_SALARY INT NOT NULL DEFAULT 1000
);

CREATE USER "USER1" IDENTIFIED BY "1234";

GRANT INSERT ON EMPLOYEES TO "USER1";
GRANT SELECT ON EMPLOYEES TO "USER1";

SELECT * FROM EMPLOYEES;
INSERT INTO EMPLOYEES VALUES (103,"E3",30000);

REVOKE INSERT ON EMPLOYEES FROM "USER1";