CREATE DATABASE DBB20;
USE DBB20;

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL,
    AGE INT NOT NULL,
    CITY VARCHAR(20) NOT NULL
);
INSERT INTO employees VALUES
(1, 'Alice',   'HR',        40000, 28, 'Delhi'),
(2, 'Bob',     'IT',        60000, 32, 'Mumbai'),
(3, 'Charlie', 'Finance',   55000, 29, 'Bangalore'),
(4, 'Diana',   'IT',        62000, 35, 'Mumbai'),
(5, 'Eve',     'HR',        42000, 26, 'Chennai'),
(6, 'Frank',   'Finance',   53000, 31, 'Delhi'),
(7, 'Grace',   'IT',        58000, 30, 'Hyderabad');
SELECT * FROM EMPLOYEES;

SELECT NAME,
	(SELECT AVG(SALARY) FROM EMPLOYEES) AS AVG_SALARY
FROM EMPLOYEES;
SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT NAME,SALARY,
	(SELECT MAX(SALARY) FROM EMPLOYEES) - SALARY AS DIFF_SALARY
FROM EMPLOYEES;
SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT NAME,SALARY,
	(SELECT AVG(SALARY) FROM EMPLOYEES) - SALARY AS DIFF_SAALRY
FROM EMPLOYEES;
SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);
SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE SALARY = (
	SELECT MIN(SALARY) FROM EMPLOYEES
	WHERE DEPARTMENT = "FINANCE"
);
SELECT MIN(SALARY) FROM EMPLOYEES
WHERE DEPARTMENT = "FINANCE";


SELECT * FROM EMPLOYEES
WHERE CITY = (
	SELECT CITY FROM EMPLOYEES
    WHERE EMP_ID = 1
    );
SELECT CITY FROM EMPLOYEES
WHERE EMP_ID = 1;

SELECT * FROM EMPLOYEES
WHERE AGE < (
	SELECT MAX(AGE) FROM EMPLOYEES
	WHERE DEPARTMENT = "IT"
);
SELECT MAX(AGE) FROM EMPLOYEES
WHERE DEPARTMENT = "IT";

SELECT * FROM EMPLOYEES
WHERE SALARY > (
	SELECT SALARY FROM EMPLOYEES
	WHERE NAME = "Eve"
);
SELECT SALARY FROM EMPLOYEES
WHERE NAME = "Eve";


SELECT * FROM EMPLOYEES
WHERE SALARY > (
	SELECT AVG(SALARY) FROM EMPLOYEES
);
SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE CITY = (
	SELECT CITY FROM EMPLOYEES
	WHERE EMP_ID = 5
);

SELECT * FROM EMPLOYEES
WHERE AGE > (
	SELECT MIN(AGE) FROM EMPLOYEES
    WHERE DEPARTMENT = "FINANCE"
);

SELECT * FROM EMPLOYEES
WHERE SALARY > (
	SELECT MAX(SALARY) FROM EMPLOYEES
	WHERE DEPARTMENT = "HR"
);

SELECT * FROM EMPLOYEES
WHERE SALARY < (
	SELECT SALARY FROM EMPLOYEES
    WHERE NAME = "Diana"
);

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = (
	SELECT DEPARTMENT FROM EMPLOYEES
    WHERE NAME = "CHARLIE"
);

SELECT * FROM EMPLOYEES
WHERE CITY = (
	SELECT CITY FROM EMPLOYEES
    WHERE SALARY = (
		SELECT MIN(SALARY) FROM EMPLOYEES
	)
);

SELECT * FROM EMPLOYEES
WHERE AGE > (
	SELECT AVG(AGE) FROM EMPLOYEES
    WHERE DEPARTMENT = "IT"
);

SELECT * FROM EMPLOYEES
WHERE SALARY = (
	SELECT MIN(SALARY) FROM EMPLOYEES
);

SELECT * FROM EMPLOYEES
WHERE AGE = (
	SELECT MAX(AGE) FROM EMPLOYEES
);
