CREATE DATABASE DB6;
USE DB6;

CREATE TABLE PRODUCTS(
	ID INT,
    NAME VARCHAR(20),
    PRICE INT,
    QTY INT
);
INSERT INTO Products VALUES
(1, 'Pen', 10.00, 100),
(2, 'Notebook', 25.00, 50),
(3, 'Pencil', 5.00, 200),
(4, 'Eraser', 3.00, 300),
(5, 'Marker', 15.00, 80);

SELECT *,PRICE*QTY AS TOTAL_VALUE FROM PRODUCTS;
SELECT ID,NAME,PRICE-5 AS PRICE,QTY FROM PRODUCTS;
SELECT ID,NAME,PRICE*10 AS PRICE_FOR_10_PRODUCTS FROM PRODUCTS;
SELECT * FROM PRODUCTS WHERE QTY%50=0;

SELECT * FROM PRODUCTS;
SET SQL_SAFE_UPDATES = 0;

UPDATE PRODUCTS SET QTY = QTY+2;
SELECT * FROM PRODUCTS;
UPDATE PRODUCTS SET PRICE = PRICE-5;
SELECT * FROM PRODUCTS;
UPDATE PRODUCTS SET QTY = QTY * 2 WHERE NAME = "Eraser";
SELECT * FROM PRODUCTS;
DELETE FROM PRODUCTS WHERE QTY < 100;
SELECT * FROM PRODUCTS;

CREATE TABLE STUDENTSCORE(
	ID INT,
    NAME VARCHAR(100),
    SUBJECT VARCHAR(20),
    MARKS INT
);
INSERT INTO StudentScore VALUES
(1, 'Alice', 'Math', 95),
(2, 'Bob', 'Math', 76),
(3, 'Charlie', 'Math', 59),
(4, 'Diana', 'Math', 88),
(5, 'Eve', 'Math', 40),
(6, 'Frank', 'Math', 95);
SELECT * FROM STUDENTSCORE;


SELECT * FROM STUDENTSCORE WHERE MARKS > 80;
SELECT * FROM STUDENTSCORE WHERE MARKS >= 60;
SELECT * FROM STUDENTSCORE WHERE MARKS < 50;
SELECT * FROM STUDENTSCORE WHERE MARKS = 95;
SELECT * FROM STUDENTSCORE WHERE MARKS != 95;
SELECT * FROM STUDENTSCORE WHERE MARKS <= 60;

UPDATE STUDENTSCORE SET MARKS = MARKS + 10 WHERE MARKS < 60;
SELECT * FROM STUDENTSCORE;
UPDATE STUDENTSCORE SET MARKS = MARKS + 5 WHERE MARKS <= 60;
SELECT * FROM STUDENTSCORE;
UPDATE STUDENTSCORE SET MARKS = MARKS + 2 WHERE MARKS > 90;
SELECT * FROM STUDENTSCORE;
UPDATE STUDENTSCORE SET MARKS = MARKS + 3 WHERE MARKS >= 80;
SELECT * FROM STUDENTSCORE;
UPDATE STUDENTSCORE SET MARKS = MARKS - 1 WHERE MARKS != 95;
SELECT * FROM STUDENTSCORE;
UPDATE STUDENTSCORE SET MARKS = 100 WHERE MARKS = 99;
SELECT * FROM STUDENTSCORE;

DELETE FROM STUDENTSCORE WHERE MARKS < 60;
SELECT * FROM STUDENTSCORE;
DELETE FROM STUDENTSCORE WHERE MARKS >=90;
SELECT * FROM STUDENTSCORE;
DELETE FROM STUDENTSCORE WHERE MARKS != 95;
DELETE FROM STUDENTSCORE WHERE MARKS = 76;


CREATE TABLE EMPLOYEES(
	ID INT,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(15),
    SALARY INT,
    ISACTIVE BOOL
);
INSERT INTO EMPLOYEES VALUES 
(101,"E1","IT",60000,TRUE),
(102,"E2","HR",70000,TRUE),
(103,"E3","IT",55000,FALSE),
(104,"E4","HR",45000,FALSE),
(105,"E6","SALES",34000,TRUE),
(106,"E7","SALES",10000,FALSE);
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT = "IT" AND SALARY > 40000;
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT="HR" OR SALARY < 35000;
SELECT * FROM EMPLOYEES
WHERE NOT DEPARTMENT = "HR";
SELECT * FROM EMPLOYEES
WHERE (DEPARTMENT = "SALES" OR SALARY > 30000) AND ISACTIVE = TRUE;

SELECT * FROM EMPLOYEES;
UPDATE EMPLOYEES SET SALARY = SALARY + 2000
WHERE DEPARTMENT = "IT" AND ISACTIVE = TRUE;

UPDATE EMPLOYEES SET SALARY = SALARY - SALARY * 0.10
WHERE ISACTIVE = FALSE;
SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES SET ISACTIVE = FALSE
WHERE NOT DEPARTMENT = "IT";
SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES
WHERE DEPARTMENT = "HR" AND ISACTIVE = FALSE;

DELETE FROM EMPLOYEES
WHERE DEPARTMENT = "FINANACE" OR SALARY < 35000;

DELETE FROM EMPLOYEES
WHERE NOT DEPARTMENT = "IT";
